### ISSUE TITLE
ticker doesn't close the channel after calling Stop()

### ISSUE THREAD

**Issue by vikstrous** [WatchBeam/clock#1]
Repro:

```go
package main

import (
	"sync"
	"time"

	"github.com/WatchBeam/clock"
)

func main() {
	c := clock.NewMockClock(time.Now())
	ticker := c.NewTicker(time.Second)
	ch := ticker.Chan()
	wg := sync.WaitGroup{}
	wg.Add(1)
	go func() {
		for range ch {
		}
		wg.Done()
	}()
	ticker.Stop()
	wg.Wait()
}
```

**Comment by connor4312** [comment]
Hi, thanks for the PR!

This package mirrors the standard library which [specifies](https://golang.org/pkg/time/#Ticker.Stop) that the channel is not closed "to prevent a read from the channel succeeding incorrectly".

**Comment by vikstrous** [comment]
Interesting. I hadn't tried it with a real timer. I guess I need to signal my goroutine to end some other way. Feel free to close this PR and the issue.

On July 5, 2016 6:56:42 PM PDT, Connor Peet <notifications@github.com> wrote:
>Hi, thanks for the PR!
>
>This package mirrors the standard library which
>[specifies](https://golang.org/pkg/time/#Ticker.Stop) that the channel
>is not closed "to prevent a read from the channel succeeding
>incorrectly". 
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/WatchBeam/clock/issues/1#issuecomment-230652518

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
